version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin[123]
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    

  # web:
  #   build: 
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3200:3000"
  #   restart: always
  #   networks:
  #     - avlp-network
  # be:
  #   build: 
  #     context: ./Backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9899:9898"
  #   restart: always
  #   networks:
  #     - avlp-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:

networks:
  avlp-network:
