version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - avlp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin[123]
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./Backend/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - avlp-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: go_app_container
    depends_on:
      - postgres
    ports:
      - "9898:9898"
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: "5432"
    networks:
      - avlp-network
    

volumes:
  postgres_data:
  pgadmin_data:

networks:
  avlp-network:
    driver: bridge