version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avlp0
    ports:
      - "5432:5432"
    volumes:
      - pg-volumes:/var/lib/postgresql/data
    restart: always
    

  # web:
  #   build: 
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3200:3000"
  #   restart: always
  #   networks:
  #     - avlp-network
  # be:
  #   build: 
  #     context: ./Backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9899:9898"
  #   restart: always
  #   networks:
  #     - avlp-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  pgadmin:
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin[123]
      ports:
        - "5050:80"
      restart: always
      networks:
        - avlp-network
      depends_on:
        - postgres
volumes:
  pg-volumes:

networks:
  avlp-network:
    driver: bridge