services:
  postgres:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avlp-db0
    volumes:
      - pg-volumes:/var/lib/postgresql/data
    restart: always
    networks:
      - avlp-network
  web:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3200:3000"
    restart: always
    networks:
      - avlp-network
  be:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9899:9898"
    restart: always
    networks:
      - avlp-network
    depends_on:
      - postgres
volumes:
  pg-volumes:

networks:
  avlp-network: