basePath: /
definitions:
  models.Class:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      img:
        type: string
      isPublic:
        type: boolean
      max_player:
        type: integer
      owner:
        allOf:
        - $ref: '#/definitions/models.User'
        description: Relationship
      owner_id:
        description: Foreign key
        type: integer
      topic:
        type: string
      updated_at:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.User:
    properties:
      bio:
        type: string
      created_at:
        type: string
      deleted_at:
        description: Nullable field
        type: string
      discord:
        type: string
      email:
        type: string
      github:
        type: string
      id:
        type: integer
      linkedin:
        type: string
      name:
        type: string
      password:
        type: string
      profile_picture:
        type: string
      updated_at:
        type: string
      username:
        type: string
      youtube:
        type: string
    type: object
host: localhost:9898
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for managing users, classes, and assembly-related functionality
    in the Assembly Visual Learning Platform
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Assembly Visual Learning Platform API
  version: "1.0"
paths:
  /classes:
    get:
      description: Retrieve a list of all classes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Class'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all classes
      tags:
      - Classes
    post:
      consumes:
      - multipart/form-data
      description: Create a new class with the provided details and an optional image
      parameters:
      - description: Class topic
        in: formData
        name: topic
        required: true
        type: string
      - description: Class description
        in: formData
        name: description
        type: string
      - description: Maximum number of players
        in: formData
        name: max_player
        required: true
        type: integer
      - description: Whether the class is public
        in: formData
        name: is_public
        type: boolean
      - description: Class image
        in: formData
        name: img
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new class
      tags:
      - Classes
  /classes/{id}:
    delete:
      description: Delete a class by its ID
      parameters:
      - description: Class ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete a class
      tags:
      - Classes
    get:
      description: Retrieve a class by its ID
      parameters:
      - description: Class ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a class by ID
      tags:
      - Classes
    put:
      consumes:
      - multipart/form-data
      description: Update a class with the provided details and an optional image
      parameters:
      - description: Class ID
        in: path
        name: id
        required: true
        type: integer
      - description: Class topic
        in: formData
        name: topic
        type: string
      - description: Class description
        in: formData
        name: description
        type: string
      - description: Maximum number of players
        in: formData
        name: max_player
        type: integer
      - description: Whether the class is public
        in: formData
        name: is_public
        type: boolean
      - description: Class image
        in: formData
        name: img
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Class'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update a class
      tags:
      - Classes
securityDefinitions:
  BearerAuth:
    description: '"Enter the token with the `Bearer ` prefix, e.g., `Bearer <token>`"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
